# Generated by Django 4.2.3 on 2024-10-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_saved_products'),
        ('userauths', '0003_profile_facebook_profile_instagram_profile_whatsapp_and_more'),
    ]

    operations = [
    ]
