# Generated by Django 4.2.3 on 2024-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used'), ('old', 'old'), ('refurbished', 'refurbished'), ('renovated', 'renovated')], default='none', max_length=50),
        ),
    ]
