# Generated by Django 5.0 on 2024-10-01 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('deposited', 'Deposited'), ('purchased', 'purchased')], max_length=10),
        ),
    ]
