# Generated by Django 5.0 on 2024-10-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wallettransaction_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('deposited', 'Deposited'), ('purchased', 'purchased'), ('bought', 'bought')], max_length=10),
        ),
    ]
