# Generated by Django 4.2.3 on 2024-08-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
