# Generated by Django 5.0 on 2024-10-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_tags_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
