# Generated by Django 4.2.3 on 2024-10-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_stream_likes_follow'),
        ('core', '0008_rename_tag_product_tags'),
    ]

    operations = [
    ]
